import time
input("готов?")
time.sleep(1)
print(5)
time.sleep(1)
print(4)
time.sleep(1)
print(3)
time.sleep(1)
print(2)
time.sleep(1)
print(1)
time.sleep(1)
print(0)
time.sleep(1)
import turtle
turtle.fillcolor("purple")
turtle.begin_fill()
turtle.forward(100)
turtle.right(-120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.end_fill()
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.left(-60)
turtle.forward(120)
turtle.right(-90)
turtle.forward(80)
turtle.left(90)
turtle.forward(120)
turtle.right(-90)
turtle.forward(80)
turtle.end_fill()
turtle.right(90)
turtle.penup()
turtle.forward(150)
turtle.pendown()
turtle.fillcolor("grey")
turtle.begin_fill()
turtle.left(-90)
turtle.forward(100)
turtle.right(-90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.right(-90)
turtle.forward(100)
turtle.end_fill()








